Refactor/refactor 1213
smartmind-team/thanosql-ai-chat pull request #1
Opened 2024-12-18 08:41 UTC by Jin-Doh

2024-12-18 12:05 UTC, nokchalatte requested changes

2024-12-18 12:05 UTC, nokchalatte commented on pyproject.toml
> +python = ">=3.9,<3.14"
X | Y union types are only introduced in Python 3.10 (https://docs.python.org/3/whatsnew/3.10.html#:~:text=PEP%20604%2C%20Allow%20writing%20union%20types%20as%20X%20%7C%20Y), so either upgrade this requirement or remove all references to that style

2024-12-19 00:19 UTC, Jin-Doh commented on .gitignore
> +
네 확인했습니다 해당 내용 반영해서 신규 커밋 올리겠습니다

2024-12-19 00:20 UTC, Jin-Doh commented on .pre-commit-config.yaml
> +    rev: v3.19.1
fix commit들에서는 실행하지 않았습니다
수정 commit 올릴 때 pre-commit 실행 후 다시 올리겠습니다!

2024-12-19 00:22 UTC, Jin-Doh commented on docker/dev.docker-compose.yml
> +      dockerfile: docker/Dockerfile
해당 내용은 poetry를 활용한 의존성 관리로 변경되면서 루트 디렉토리에 위치한 `pyproject.toml`과 `pyproject.lock`을 빌드 과정에서 `be` 컨테이너 내부에 복사하기 위해 context를 루트 디렉토리를 이전했습니다
해당 과정에서 Dockerfile의 상대경로가 변경되면서 `docker/Dockerfile`로 변경했습니다

2024-12-19 00:23 UTC, Jin-Doh commented on app/models/schema/chat/__init__.py
> +class ChatRequest(BaseModel):
Oh, I don't know about WPS412. It will be modify in next commit
Thank you!

2024-12-19 00:24 UTC, Jin-Doh commented on tests/test-chat.py
> +PATH = "/chat"
현재 테스트 코드는 임시로 확인할 때 만들었던 것들이라 재작성 예정입니다
tests 디렉토리를 제외했어야 했는데 깜빡했습니다 :(

2024-12-19 00:24 UTC, Jin-Doh commented on tests/test-chat.py
> +    test_chat()
same with [above comments](https://github.com/smartmind-team/thanosql-ai-chat/pull/1#discussion_r1890984052)

2024-12-19 00:29 UTC, Jin-Doh commented on app/utils/logger.py
> +    def _get_level(self, lv: Union[int, str]):
I agree reducing dependencies is a better way to go in the long run. I'll fix that in the next commit!

2024-12-19 00:29 UTC, Jin-Doh commented on pyproject.toml
> +python = ">=3.9,<3.14"
Okay, thank you! I will fix in next commit!

2024-12-19 01:20 UTC, nokchalatte commented on docker/dev.docker-compose.yml
> +      dockerfile: docker/Dockerfile
그러면 이렇게 `build: docker` 쓰면 더 낫지 않나요..?

2024-12-19 02:15 UTC, Jin-Doh commented on docker/dev.docker-compose.yml
> +      dockerfile: docker/Dockerfile
@nokchalatte `build: docker`를 사용하게 될 경우, build context가 `docker` 디렉토리로 고정되게 됩니다
이럴 경우 `root` 디렉토리에 위치한 `pyproject.toml`과 `pyproject.lock`을 인식하지 못합니다.

만약 이를 위해 해당 파일들을 `docker` 디렉토리로 옮기게 되면, 이는 project_root 디렉토리에 위치해야 하는 poetry 관리 규칙에 어긋나게 됩니다.

2024-12-19 03:01 UTC, closed without merging